server:
  port: 8083

spring:
  application:
    name: journal-service
  datasource:
    url: jdbc:postgresql://localhost/db_name
    username: db_username
    password: db_password
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/